<?php

declare(strict_types=1);

/*
 * Pakistan — Province → District → Tehsils
 * Used for 3-level cascading dropdowns on checkout.
 */

return [

    'Punjab' => [
        'Attock'          => ['Attock', 'Fateh Jang', 'Hazro', 'Jand', 'Pindigheb'],
        'Bahawalnagar'    => ['Bahawalnagar', 'Chishtian', 'Fort Abbas', 'Hasilpur', 'Minchinabad', 'Yazman'],
        'Bahawalpur'      => ['Ahmadpur East', 'Bahawalpur', 'Hasilpur', 'Khairpur Tamewali', 'Yazman'],
        'Bhakkar'         => ['Bhakkar', 'Darya Khan', 'Kallur Kot', 'Mankera'],
        'Chakwal'         => ['Chakwal', 'Choa Saidan Shah', 'Talagang'],
        'Chiniot'         => ['Bhawana', 'Chiniot', 'Lalian'],
        'Dera Ghazi Khan' => ['Dera Ghazi Khan', 'Kot Chutta', 'Taunsa', 'Vehova'],
        'Faisalabad'      => ['Chak Jhumra', 'Faisalabad', 'Jaranwala', 'Samundri', 'Tandlianwala'],
        'Gujranwala'      => ['Gujranwala', 'Kamoke', 'Nowshera Virkan', 'Wazirabad'],
        'Gujrat'          => ['Gujrat', 'Kharian', 'Sarai Alamgir'],
        'Hafizabad'       => ['Hafizabad', 'Pindi Bhattian', 'Sukheke'],
        'Jhang'           => ['Ahmad Pur Sial', 'Jhang', 'Shorkot'],
        'Jhelum'          => ['Jhelum', 'Pind Dadan Khan', 'Sohawa'],
        'Kasur'           => ['Chunian', 'Kasur', 'Kot Radha Kishan', 'Pattoki'],
        'Khanewal'        => ['Kabirwala', 'Khanewal', 'Mian Channu', 'Tulamba'],
        'Khushab'         => ['Khushab', 'Noorpur', 'Quaidabad'],
        'Lahore'          => ['Lahore City', 'Lahore Cantonment', 'Model Town', 'Raiwind', 'Shalimar'],
        'Layyah'          => ['Chaubara', 'Karor', 'Layyah'],
        'Lodhran'         => ['Dunyapur', 'Kehror Pakka', 'Lodhran'],
        'Mandi Bahauddin' => ['Malikwal', 'Mandi Bahauddin', 'Phalia'],
        'Mianwali'        => ['Essa Khel', 'Mianwali', 'Piplan'],
        'Multan'          => ['Jalalpur Pirwala', 'Multan', 'Shujabad', 'Shumali'],
        'Muzaffargarh'    => ['Ali Pur', 'Jatoi', 'Kot Addu', 'Muzaffargarh'],
        'Nankana Sahib'   => ['Nankana Sahib', 'Sangla Hill', 'Shahkot'],
        'Narowal'         => ['Narowal', 'Shakargarh', 'Zafarwal'],
        'Okara'           => ['Depalpur', 'Okara', 'Renala Khurd'],
        'Pakpattan'       => ['Arifwala', 'Pakpattan'],
        'Rahim Yar Khan'  => ['Khan Pur', 'Liaqatpur', 'Rahim Yar Khan', 'Sadiqabad'],
        'Rajanpur'        => ['Jampur', 'Rajanpur', 'Rojhan'],
        'Rawalpindi'      => ['Gujar Khan', 'Kahuta', 'Kotli Sattian', 'Murree', 'Rawalpindi', 'Taxila'],
        'Sahiwal'         => ['Chichawatni', 'Sahiwal'],
        'Sargodha'        => ['Bhalwal', 'Kot Momin', 'Sargodha', 'Shah Pur', 'Sillanwali'],
        'Sheikhupura'     => ['Ferozewala', 'Muridke', 'Safdarabad', 'Sheikhupura'],
        'Sialkot'         => ['Daska', 'Pasrur', 'Sambrial', 'Sialkot'],
        'Toba Tek Singh'  => ['Gojra', 'Kamalia', 'Pir Mahal', 'Toba Tek Singh'],
        'Vehari'          => ['Burewala', 'Mailsi', 'Vehari'],
    ],

    'Sindh' => [
        'Badin'               => ['Badin', 'Matli', 'Talhar', 'Tando Bago'],
        'Dadu'                => ['Dadu', 'Johi', 'Khairpur Nathan Shah', 'Mehar', 'Sehwan'],
        'Ghotki'              => ['Daharki', 'Ghotki', 'Kandhkot', 'Mirpur Mathelo', 'Ubauro'],
        'Hyderabad'           => ['Hyderabad', 'Latifabad', 'Qasimabad', 'Kotri'],
        'Jacobabad'           => ['Jacobabad', 'Garhi Khairo', 'Thull'],
        'Jamshoro'            => ['Jamshoro', 'Kotri', 'Manjhand', 'Sehwan'],
        'Kambar Shahdadkot'   => ['Kambar', 'Miro Khan', 'Qambar', 'Shahdadkot', 'Warah'],
        'Karachi'             => ['Defence', 'Gulshan-e-Iqbal', 'Gulberg', 'Kemari', 'Korangi', 'Landhi', 'Lyari', 'Malir', 'North Nazimabad', 'Orangi Town', 'Saddar'],
        'Kashmore'            => ['Kashmore', 'Kandhkot', 'Tangwani'],
        'Khairpur'            => ['Khairpur', 'Kot Diji', 'Kingri', 'Nara', 'Sobhodero', 'Thari Mirwah'],
        'Larkana'             => ['Dokri', 'Kamber', 'Larkana', 'Ratodero'],
        'Matiari'             => ['Hala', 'Matiari', 'Saeedabad'],
        'Mirpur Khas'         => ['Digri', 'Jhuddo', 'Kot Ghulam Muhammad', 'Mirpur Khas', 'Umerkot'],
        'Naushahro Feroze'    => ['Bhiria', 'Kandiaro', 'Moro', 'Naushahro Feroze'],
        'Sanghar'             => ['Khipro', 'Sanghar', 'Shahdadpur', 'Sinjhoro', 'Tando Adam'],
        'Shaheed Benazirabad' => ['Daulatpur', 'Nawabshah', 'Qazi Ahmad', 'Sakrand'],
        'Shikarpur'           => ['Garhi Yasin', 'Lakhi', 'Shikarpur'],
        'Sujawal'             => ['Jati', 'Mirpur Bathoro', 'Sujawal', 'Thatta'],
        'Sukkur'              => ['Pano Aqil', 'Rohri', 'Saleh Pat', 'Sukkur'],
        'Tando Allah Yar'     => ['Chamber', 'Tando Allah Yar'],
        'Tando Muhammad Khan' => ['Tando Muhammad Khan'],
        'Tharparkar'          => ['Chachro', 'Dahli', 'Diplo', 'Islamkot', 'Mithi', 'Nagarparkar'],
        'Thatta'              => ['Ghorabari', 'Jati', 'Keti Bandar', 'Mirpur Sakro', 'Thatta'],
        'Umerkot'             => ['Kunri', 'Pithoro', 'Samaro', 'Umerkot'],
    ],

    'Khyber Pakhtunkhwa' => [
        'Abbottabad'       => ['Abbottabad', 'Havelian', 'Lora', 'Nathiagali'],
        'Bajaur'           => ['Khar', 'Mamund', 'Nawagai', 'Salarzai'],
        'Bannu'            => ['Bannu', 'Domel', 'Pezu'],
        'Battagram'        => ['Allai', 'Battagram', 'Puran'],
        'Buner'            => ['Buner', 'Daggar', 'Gadezai', 'Mandanr'],
        'Charsadda'        => ['Charsadda', 'Shabqadar', 'Tangi'],
        'Chitral'          => ['Chitral', 'Drosh', 'Mastuj', 'Mulkhow', 'Torkhow'],
        'Dera Ismail Khan' => ['Darazinda', 'Dera Ismail Khan', 'Kulachi', 'Paharpur', 'Paroa'],
        'Dir Lower'        => ['Adenzai', 'Balambat', 'Chakdara', 'Dir', 'Khal', 'Timergara'],
        'Dir Upper'        => ['Kumrat', 'Wari'],
        'Hangu'            => ['Hangu', 'Thall'],
        'Haripur'          => ['Ghazi', 'Haripur', 'Khanpur'],
        'Karak'            => ['Banda Daud Shah', 'Karak', 'Takht-e-Nasrati'],
        'Khyber'           => ['Bara', 'Jamrud', 'Landi Kotal'],
        'Kohat'            => ['Kohat', 'Lachi', 'Thal'],
        'Kohistan'         => ['Allai', 'Kolai', 'Pattan'],
        'Kurram'           => ['Lower Kurram', 'Upper Kurram'],
        'Lakki Marwat'     => ['Lakki Marwat', 'Serai Naurang'],
        'Malakand'         => ['Batkhela', 'Dargai', 'Malakand'],
        'Mansehra'         => ['Balakot', 'Mansehra', 'Oghi', 'Pakhal'],
        'Mardan'           => ['Katlang', 'Mardan', 'Rustam', 'Takht Bhai'],
        'Mohmand'          => ['Baizai', 'Ekkaghund', 'Prang Ghar'],
        'North Waziristan' => ['Mir Ali', 'Miranshah', 'Razmak'],
        'Nowshera'         => ['Akora Khattak', 'Jehangira', 'Nowshera', 'Pabbi'],
        'Orakzai'          => ['Central Orakzai', 'Lower Orakzai', 'Upper Orakzai'],
        'Peshawar'         => ['Badaber', 'Chamkani', 'Peshawar', 'Regi', 'Shah Alam'],
        'Shangla'          => ['Alpuri', 'Besham', 'Chakesar', 'Martung'],
        'South Waziristan' => ['Ladha', 'Sararogha', 'Wana'],
        'Swabi'            => ['Lahor', 'Razzar', 'Swabi', 'Topi'],
        'Swat'             => ['Bahrain', 'Barikot', 'Charbagh', 'Kabal', 'Khwazakhela', 'Madyan', 'Matta', 'Mingora'],
        'Tank'             => ['Tank'],
        'Tor Ghar'         => ['Banda', 'Tor Ghar'],
    ],

    'Balochistan' => [
        'Awaran'    => ['Awaran', 'Jhal Jhao', 'Mashkel'],
        'Barkhan'   => ['Barkhan', 'Rakhni', 'Sanjawi'],
        'Chagai'    => ['Chagai', 'Dalbandin', 'Nok Kundi'],
        'Dera Bugti'=> ['Dera Bugti', 'Phelawagh', 'Sui'],
        'Gwadar'    => ['Gwadar', 'Jiwani', 'Ormara', 'Pasni'],
        'Harnai'    => ['Harnai', 'Shahrig'],
        'Jaffarabad'=> ['Dera Allahyar', 'Gandava', 'Jaffarabad'],
        'Jhal Magsi'=> ['Gandava', 'Jhal Magsi'],
        'Kalat'     => ['Kalat', 'Mangochar', 'Surab'],
        'Kech'      => ['Buleda', 'Mand', 'Turbat'],
        'Kharan'    => ['Kharan', 'Nag', 'Washuk'],
        'Khuzdar'   => ['Khuzdar', 'Ornach', 'Zehri'],
        'Kohlu'     => ['Kohlu', 'Maiwand'],
        'Lasbela'   => ['Bela', 'Hub', 'Lasbela', 'Uthal', 'Winder'],
        'Loralai'   => ['Bori', 'Duki', 'Loralai', 'Mekhtar'],
        'Mastung'   => ['Dasht', 'Karakh', 'Mastung'],
        'Musakhel'  => ['Kingri', 'Musakhel'],
        'Nasirabad' => ['Dera Murad Jamali', 'Nasirabad', 'Tamboo'],
        'Nushki'    => ['Nushki'],
        'Panjgur'   => ['Gichk', 'Panjgur'],
        'Pishin'    => ['Karezat', 'Pishin', 'Quetta (Suburbs)', 'Saranan'],
        'Quetta'    => ['Quetta', 'Quetta Cantonment'],
        'Sherani'   => ['Sherani', 'Zhob'],
        'Sibi'      => ['Lehri', 'Sibi', 'Sanni'],
        'Sohbatpur' => ['Jahoo', 'Sohbatpur'],
        'Washuk'    => ['Kharan', 'Washuk'],
        'Zhob'      => ['Qamardin Karez', 'Zhob'],
        'Ziarat'    => ['Kawas', 'Ziarat'],
    ],

    'Islamabad Capital Territory' => [
        'Islamabad' => ['Bara Kahu', 'Golra', 'Islamabad City', 'Kahuta', 'Lohi Bher', 'Noon', 'Rawat', 'Sihala'],
    ],

    'Azad Jammu & Kashmir' => [
        'Bagh'         => ['Bagh', 'Dhirkot', 'Haveli'],
        'Bhimber'      => ['Bhimber', 'Samahni'],
        'Hattian Bala' => ['Hattian Bala', 'Kahuta', 'Leepa'],
        'Haveli'       => ['Forward Kahuta', 'Haveli'],
        'Kotli'        => ['Charhoi', 'Kotli', 'Sehnsa', 'Tandar'],
        'Mirpur'       => ['Chakswari', 'Mirpur', 'Palandri'],
        'Muzaffarabad' => ['Muzaffarabad', 'Nela', 'Patika'],
        'Neelum'       => ['Athmuqam', 'Kel', 'Sharda'],
        'Poonch'       => ['Poonch', 'Rawlakot', 'Thorar'],
        'Rawlakot'     => ['Banjosa', 'Rawlakot'],
        'Sudhnati'     => ['Pallandri', 'Sudhnati'],
    ],

    'Gilgit-Baltistan' => [
        'Astore'   => ['Astore', 'Gurikot'],
        'Diamer'   => ['Chilas', 'Darel', 'Tangir'],
        'Ghanche'  => ['Ghanche', 'Kharmang', 'Saltoro'],
        'Ghizer'   => ['Gahkuch', 'Ghizer', 'Ishkoman', 'Punial'],
        'Gilgit'   => ['Gilgit', 'Gupis'],
        'Hunza'    => ['Aliabad', 'Karimabad', 'Nagar'],
        'Kharmang' => ['Kharmang', 'Tolti'],
        'Nagar'    => ['Nagar', 'Sumayar'],
        'Shigar'   => ['Shigar', 'Shigar Valley'],
        'Skardu'   => ['Khaplu', 'Rondu', 'Skardu'],
    ],

];
